# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.brochure_uploader:
        class: ESPRITPIDEV\UserExpBundle\FileUploader
        arguments: ['%brochures_directory%']
