complaints_index:
    path:     /admin/
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:index" }
    methods:  GET
complaints_users_index:
    path:     /admin/displayusers
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:displayUsers" }
    methods:  GET
complaints_all_users_index:
    path:     /user/displayallusers
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:displayAllUsers" }
    methods:  GET
complaints_single_users_index:
    path:     /admin/{id}/displaysingleusers
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:displayComplaintsPerUser" }
    methods:  GET
complaints_pending:
    path:     /admin/displaypendingcomplaints
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:displayPendingComplaints" }
    methods:  GET
complaints_all_users_admin:
    path:     /admin/displayallusersadmin
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:displayAllUsersAdmin" }
    methods:  GET
complaints_show:
    path:     /admin/{id}/show
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:show" }
    methods:  GET
complaints_seen:
    path:     /admin/displayseencomplaints
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:displaySeenComplaints" }
    methods:  GET
complaints_test_charts:
    path:     /admin/complaintspermonth
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:chart" }
    methods:  [GET, POST]
complaints_animal_pie_chart:
    path:     /admin/animalpiechart
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:animalchart" }
    methods:  [GET, POST]
complaints_music_pie_chart:
    path:     /admin/musictastedrilldown
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:drilldown" }
    methods:  [GET, POST]
complaints_mail_homepage:
    path:     /admin/mailwrite
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Mail:index" }
    methods:  [GET, POST]
complaints_mail_success:
    path:     /admin/mailsuccess
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Mail:success" }
    methods:  [GET, POST]
complaints_warning:
    path:     /admin/{id}/warning
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:warning" }
    methods:  [GET, POST]
complaints_answer:
    path:     /admin/{id}/answer
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:new" }
    methods:  [GET, POST]
complaints_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:delete" }
    methods:  DELETE

complaints_my_complaints:
    path:     /user/displaymycomplaints
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:displayMyComplaints" }
    methods:  GET
complaints_show_user:
    path:     /user/{id}/showuser
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:showuser" }
    methods:  GET
complaints_success_show:
    path:     /user/{id}/successshow
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:successShow" }
    methods:  GET
complaints_new:
    path:     /user/new
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:new" }
    methods:  [GET, POST]
complaints_user_answer:
    path:     /user/{id}/answeruser
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:newuser" }
    methods:  [GET, POST]

complaints_edit:
    path:     /user/{id}/edit
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Complaints:edit" }
    methods:  [GET, POST]
