
response_show:
    path:     /admin/{id}/showresponse
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:show" }
    methods:  [GET, POST]

response_new:
    path:     /admin/{id}/newresponse
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:new" }
    methods:  [GET, POST]

response_edit:
    path:     /admin//{id}/editresponse
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:edit" }
    methods:  [GET, POST]

response_index:
    path:     /admin//response
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:index" }
    methods:  GET

response_delete:
    path:     /admin//{id}/deleteresponse
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:delete" }
    methods:  DELETE

reponse_test_pagination:
    path:     /admin//testpagination
    defaults: { _controller: "ESPRITPIDEVUserExpBundle:Response:testPagination" }
    methods:  [GET, POST]
